"""1

Revision ID: 58deb99026a8
Revises: 
Create Date: 2024-12-11 17:03:56.171266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58deb99026a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.String(length=150), nullable=False),
    sa.Column('percentage_change', sa.String(length=150), nullable=False),
    sa.Column('volume_for_the_period', sa.String(length=150), nullable=False),
    sa.Column('capitalization', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###
