"""Изменено структура базы данных

Revision ID: a477494f5911
Revises: 58deb99026a8
Create Date: 2024-12-12 23:42:25.608671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a477494f5911'
down_revision: Union[str, None] = '58deb99026a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_attribute', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_crypto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('values_crypto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('values', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_crypto.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity_crypto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('crypto_currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_currency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('price', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('percentage_change', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('volume_for_the_period', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('capitalization', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crypto_currency_pkey')
    )
    op.drop_table('values_crypto')
    op.drop_table('entity_crypto')
    op.drop_table('attribute_crypto')
    # ### end Alembic commands ###
